-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fir_engine_fir_engine_Pipeline_Process_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    local_in_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    local_in_ce0 : OUT STD_LOGIC;
    local_in_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    local_out_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    local_out_ce0 : OUT STD_LOGIC;
    local_out_we0 : OUT STD_LOGIC;
    local_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fir_engine_fir_engine_Pipeline_Process_Loop is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000110";
    constant ap_const_lv16_4A : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001010";
    constant ap_const_lv16_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln32_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln32_reg_447 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln32_fu_177_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_451 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_451_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_451_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_reg_451_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_reg_456 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_229_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_471 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_471_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp5_fu_253_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp5_reg_477 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp6_fu_259_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp6_reg_482 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln41_1_fu_332_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp : string;
    attribute use_dsp of add_ln41_1_fu_332_p2 : signal is "no";
    signal add_ln41_1_reg_488 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_fu_46 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal b_fu_50 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln32_fu_171_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_b_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_18_fu_54 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_19_fu_58 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_20_fu_62 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_21_fu_66 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_22_fu_70 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_23_fu_74 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_24_fu_78 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal empty_25_fu_82 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal x_fu_222_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal local_in_ce0_local : STD_LOGIC;
    signal local_out_we0_local : STD_LOGIC;
    signal add_ln41_3_fu_353_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp of add_ln41_3_fu_353_p2 : signal is "no";
    signal local_out_ce0_local : STD_LOGIC;
    signal tmp4_fu_235_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_28_fu_241_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_neg3_fu_247_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_29_fu_310_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_neg_fu_315_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_30_fu_321_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp7_fu_326_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_26_fu_337_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_27_fu_342_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_367_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_358_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_358_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_358_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_367_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fir_engine_mac_muladd_16s_7ns_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_engine_ama_addmuladd_16s_16s_5ns_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fir_engine_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mac_muladd_16s_7ns_16s_16_4_1_U4 : component fir_engine_mac_muladd_16s_7ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_21_fu_66,
        din1 => grp_fu_358_p1,
        din2 => grp_fu_358_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_358_p3);

    ama_addmuladd_16s_16s_5ns_16s_16_4_1_U5 : component fir_engine_ama_addmuladd_16s_16s_5ns_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 5,
        din3_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => empty_19_fu_58,
        din1 => empty_23_fu_74,
        din2 => grp_fu_367_p2,
        din3 => add_ln41_1_reg_488,
        ce => ap_const_logic_1,
        dout => grp_fu_367_p4);

    flow_control_loop_pipe_sequential_init_U : component fir_engine_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    b_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln32_fu_165_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    b_fu_50 <= add_ln32_fu_171_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    b_fu_50 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    empty_18_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_18_fu_54 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_18_fu_54 <= empty_19_fu_58;
                end if;
            end if; 
        end if;
    end process;

    empty_19_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_19_fu_58 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_19_fu_58 <= empty_20_fu_62;
                end if;
            end if; 
        end if;
    end process;

    empty_20_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_20_fu_62 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_20_fu_62 <= empty_21_fu_66;
                end if;
            end if; 
        end if;
    end process;

    empty_21_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_21_fu_66 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_21_fu_66 <= empty_22_fu_70;
                end if;
            end if; 
        end if;
    end process;

    empty_22_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_22_fu_70 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_22_fu_70 <= empty_23_fu_74;
                end if;
            end if; 
        end if;
    end process;

    empty_23_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_23_fu_74 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_23_fu_74 <= empty_24_fu_78;
                end if;
            end if; 
        end if;
    end process;

    empty_24_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_24_fu_78 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_24_fu_78 <= empty_25_fu_82;
                end if;
            end if; 
        end if;
    end process;

    empty_25_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_25_fu_82 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_25_fu_82 <= x_fu_222_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_46_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_46 <= ap_const_lv16_0;
                elsif (((icmp_ln32_reg_447 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    empty_fu_46 <= empty_18_fu_54;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln41_1_reg_488 <= add_ln41_1_fu_332_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                tmp_reg_471_pp0_iter2_reg <= tmp_reg_471;
                    zext_ln32_reg_451_pp0_iter2_reg(4 downto 0) <= zext_ln32_reg_451_pp0_iter1_reg(4 downto 0);
                    zext_ln32_reg_451_pp0_iter3_reg(4 downto 0) <= zext_ln32_reg_451_pp0_iter2_reg(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln32_reg_447 <= icmp_ln32_fu_165_p2;
                tmp5_reg_477 <= tmp5_fu_253_p2;
                tmp6_reg_482 <= tmp6_fu_259_p2;
                tmp_1_reg_456 <= ap_sig_allocacmp_b_1(4 downto 4);
                tmp_reg_471 <= tmp_fu_229_p2;
                    zext_ln32_reg_451(4 downto 0) <= zext_ln32_fu_177_p1(4 downto 0);
                    zext_ln32_reg_451_pp0_iter1_reg(4 downto 0) <= zext_ln32_reg_451(4 downto 0);
            end if;
        end if;
    end process;
    zext_ln32_reg_451(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_451_pp0_iter1_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_451_pp0_iter2_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    zext_ln32_reg_451_pp0_iter3_reg(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln32_fu_171_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_b_1) + unsigned(ap_const_lv5_1));
    add_ln41_1_fu_332_p2 <= std_logic_vector(unsigned(tmp5_reg_477) + unsigned(tmp7_fu_326_p2));
    add_ln41_3_fu_353_p2 <= std_logic_vector(signed(grp_fu_367_p4) + signed(grp_fu_358_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln32_fu_165_p2)
    begin
        if (((icmp_ln32_fu_165_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln32_reg_447)
    begin
        if (((icmp_ln32_reg_447 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_b_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, b_fu_50)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_b_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_b_1 <= b_fu_50;
        end if; 
    end process;

    empty_26_fu_337_p2 <= std_logic_vector(shift_left(unsigned(tmp_reg_471_pp0_iter2_reg),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    empty_27_fu_342_p2 <= std_logic_vector(shift_left(unsigned(tmp_reg_471_pp0_iter2_reg),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    empty_28_fu_241_p2 <= std_logic_vector(shift_left(unsigned(tmp4_fu_235_p2),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    empty_29_fu_310_p2 <= std_logic_vector(shift_left(unsigned(tmp6_reg_482),to_integer(unsigned('0' & ap_const_lv16_3(16-1 downto 0)))));
    empty_30_fu_321_p2 <= std_logic_vector(shift_left(unsigned(tmp6_reg_482),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    grp_fu_358_p1 <= ap_const_lv16_4A(7 - 1 downto 0);
    grp_fu_358_p2 <= std_logic_vector(unsigned(empty_26_fu_337_p2) - unsigned(empty_27_fu_342_p2));
    grp_fu_367_p2 <= ap_const_lv16_17(5 - 1 downto 0);
    icmp_ln32_fu_165_p2 <= "1" when (ap_sig_allocacmp_b_1 = ap_const_lv5_1A) else "0";
    local_in_address0 <= zext_ln32_fu_177_p1(4 - 1 downto 0);
    local_in_ce0 <= local_in_ce0_local;

    local_in_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            local_in_ce0_local <= ap_const_logic_1;
        else 
            local_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_address0 <= zext_ln32_reg_451_pp0_iter3_reg(5 - 1 downto 0);
    local_out_ce0 <= local_out_ce0_local;

    local_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            local_out_ce0_local <= ap_const_logic_1;
        else 
            local_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    local_out_d0 <= add_ln41_3_fu_353_p2;
    local_out_we0 <= local_out_we0_local;

    local_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            local_out_we0_local <= ap_const_logic_1;
        else 
            local_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_neg3_fu_247_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(empty_28_fu_241_p2));
    p_neg_fu_315_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(empty_29_fu_310_p2));
    tmp4_fu_235_p2 <= std_logic_vector(unsigned(empty_18_fu_54) + unsigned(empty_24_fu_78));
    tmp5_fu_253_p2 <= std_logic_vector(unsigned(p_neg3_fu_247_p2) - unsigned(tmp4_fu_235_p2));
    tmp6_fu_259_p2 <= std_logic_vector(unsigned(empty_fu_46) + unsigned(empty_25_fu_82));
    tmp7_fu_326_p2 <= std_logic_vector(unsigned(p_neg_fu_315_p2) - unsigned(empty_30_fu_321_p2));
    tmp_fu_229_p2 <= std_logic_vector(unsigned(empty_20_fu_62) + unsigned(empty_22_fu_70));
    x_fu_222_p3 <= 
        ap_const_lv16_0 when (tmp_1_reg_456(0) = '1') else 
        local_in_q0;
    zext_ln32_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_b_1),64));
end behav;
