stages:
  - setup
  - simulate
  - build
  - test

# Variabili globali per non dover ripetere il percorso di Vivado
variables:
  VIVADO_EXEC: "C:\\AMDDesignTools\\2025.2\\Vivado\\bin\\vivado.bat"

# Esempio di Job 1: Creazione del progetto e IP
project_recreation:
  stage: setup
  tags:
    - fpga-arty-a7  # Usa solo il PC del laboratorio
  script:
    - echo "Avvio rigenerazione progetto e IP HLS..."
    - '%VIVADO_EXEC% -mode batch -source scripts/recreate_project.tcl'
  artifacts:
    untracked: true # Salva la cartella del progetto per i job successivi
    expire_in: 1 hour

# Esempio di Job 2: Simulazione RTL
rtl_simulation:
  stage: simulate
  tags:
    - fpga-arty-a7
  script:
    - echo "Avvio simulazione XSim..."
    - '%VIVADO_EXEC% -mode batch -source scripts/run_sim.tcl'

# Esempio di Job 3: Generazione Bitstream
bitstream_generation:
  stage: build
  tags:
    - fpga-arty-a7
  script:
    - echo "Avvio sintesi e implementazione..."
    - '%VIVADO_EXEC% -mode batch -source scripts/run_build.tcl'
  artifacts:
    paths:
      - project_3/project_3.runs/impl_1/synth_top_wrapper.bit
    expire_in: 1 week # Conserva il bitstream generato per il download

# Esempio di Job 4: Test Hardware in the Loop
hardware_in_the_loop:
  stage: test
  tags:
    - fpga-arty-a7
  script:
    - echo "Flash dell'FPGA ed esecuzione test..."
    - '%VIVADO_EXEC% -mode batch -source scripts/hil_test.tcl'