# ==========================================
# Simulation Automation Script (Demo Version)
# ==========================================

# Open the project generated by Step 1 (if not already open)
if {[catch {current_project}]} {
    open_project ./project_3/project_3.xpr
}

# Close any simulations left open in the background
close_sim -quiet

puts "=================================================================="
puts ">>> GENERATING IP SIMULATION MODELS                            <<<"
puts "=================================================================="
generate_target Simulation [get_files *.bd]
export_ip_user_files -no_script -force

# ----------------------------------------------------------------
# SIMULATION: SYSTEM TEST (FULL AXI SoC)
# ----------------------------------------------------------------
puts "=================================================================="
puts ">>> STARTING SIMULATION: FULL AXI SYSTEM (tb_axi_system_fsm)   <<<"
puts "=================================================================="
set_property top tb_axi_system_fsm [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
update_compile_order -fileset sim_1

launch_simulation
close_sim -quiet

puts "=================================================================="
puts ">>> SIMULATION COMPLETED SUCCESSFULLY!                           <<<"
puts "=================================================================="