# ==========================================
# Simulation Automation Script
# ==========================================

# Open the project generated by Step 1 (if not already open)
if {[catch {current_project}]} {
    open_project ./project_3/project_3.xpr
}

# Close any simulations left open in the background
close_sim -quiet

puts "=================================================================="
puts ">>> GENERATING IP SIMULATION MODELS                            <<<"
puts "=================================================================="
generate_target Simulation [get_files *.bd]
export_ip_user_files -no_script -force

# ----------------------------------------------------------------
# SIMULATION 1: UNIT TEST FSM
# ----------------------------------------------------------------
puts "=================================================================="
puts ">>> 1. STARTING SIMULATION: ISOLATED FSM (tb_fsm)              <<<"
puts "=================================================================="
set_property top tb_fsm [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
update_compile_order -fileset sim_1
launch_simulation
close_sim -quiet

# ----------------------------------------------------------------
# SIMULATION 2: INTEGRATION TEST (FSM + FIR)
# ----------------------------------------------------------------
puts "=================================================================="
puts ">>> 2. STARTING SIMULATION: FSM + FIR (tb_system)              <<<"
puts "=================================================================="
set_property top tb_system [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
update_compile_order -fileset sim_1
launch_simulation
close_sim -quiet

# ----------------------------------------------------------------
# SIMULATION 3: SYSTEM TEST (FULL AXI SoC)
# ----------------------------------------------------------------
puts "=================================================================="
puts ">>> 3. STARTING SIMULATION: FULL AXI SYSTEM (tb_axi_system_fsm)<<<"
puts "=================================================================="
set_property top tb_axi_system_fsm [get_filesets sim_1]
set_property top_lib xil_defaultlib [get_filesets sim_1]
update_compile_order -fileset sim_1
launch_simulation
close_sim -quiet

puts "=================================================================="
puts ">>> ALL SIMULATIONS COMPLETED SUCCESSFULLY!                      <<<"
puts "=================================================================="