// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module fir_engine_fir_engine_Pipeline_Process_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        local_in_address0,
        local_in_ce0,
        local_in_q0,
        local_out_address0,
        local_out_ce0,
        local_out_we0,
        local_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] local_in_address0;
output   local_in_ce0;
input  [15:0] local_in_q0;
output  [4:0] local_out_address0;
output   local_out_ce0;
output   local_out_we0;
output  [15:0] local_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln32_fu_165_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln32_reg_447;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln32_fu_177_p1;
reg   [63:0] zext_ln32_reg_451;
reg   [63:0] zext_ln32_reg_451_pp0_iter1_reg;
reg   [63:0] zext_ln32_reg_451_pp0_iter2_reg;
reg   [63:0] zext_ln32_reg_451_pp0_iter3_reg;
reg   [0:0] tmp_1_reg_456;
wire   [15:0] tmp_fu_229_p2;
reg   [15:0] tmp_reg_471;
reg   [15:0] tmp_reg_471_pp0_iter2_reg;
wire   [15:0] tmp5_fu_253_p2;
reg   [15:0] tmp5_reg_477;
wire   [15:0] tmp6_fu_259_p2;
reg   [15:0] tmp6_reg_482;
(* use_dsp = "no" *) wire   [15:0] add_ln41_1_fu_332_p2;
reg  signed [15:0] add_ln41_1_reg_488;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_block_pp0_stage0;
reg   [15:0] empty_fu_46;
wire    ap_loop_init;
reg   [4:0] b_fu_50;
wire   [4:0] add_ln32_fu_171_p2;
reg   [4:0] ap_sig_allocacmp_b_1;
reg   [15:0] empty_18_fu_54;
reg  signed [15:0] empty_19_fu_58;
reg   [15:0] empty_20_fu_62;
reg  signed [15:0] empty_21_fu_66;
reg   [15:0] empty_22_fu_70;
reg  signed [15:0] empty_23_fu_74;
reg   [15:0] empty_24_fu_78;
reg   [15:0] empty_25_fu_82;
wire   [15:0] x_fu_222_p3;
reg    local_in_ce0_local;
reg    local_out_we0_local;
(* use_dsp = "no" *) wire   [15:0] add_ln41_3_fu_353_p2;
reg    local_out_ce0_local;
wire   [15:0] tmp4_fu_235_p2;
wire   [15:0] empty_28_fu_241_p2;
wire   [15:0] p_neg3_fu_247_p2;
wire   [15:0] empty_29_fu_310_p2;
wire   [15:0] p_neg_fu_315_p2;
wire   [15:0] empty_30_fu_321_p2;
wire   [15:0] tmp7_fu_326_p2;
wire   [15:0] empty_26_fu_337_p2;
wire   [15:0] empty_27_fu_342_p2;
wire  signed [15:0] grp_fu_367_p4;
wire  signed [15:0] grp_fu_358_p3;
wire   [6:0] grp_fu_358_p1;
wire  signed [15:0] grp_fu_358_p2;
wire   [4:0] grp_fu_367_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 empty_fu_46 = 16'd0;
#0 b_fu_50 = 5'd0;
#0 empty_18_fu_54 = 16'd0;
#0 empty_19_fu_58 = 16'd0;
#0 empty_20_fu_62 = 16'd0;
#0 empty_21_fu_66 = 16'd0;
#0 empty_22_fu_70 = 16'd0;
#0 empty_23_fu_74 = 16'd0;
#0 empty_24_fu_78 = 16'd0;
#0 empty_25_fu_82 = 16'd0;
#0 ap_done_reg = 1'b0;
end

fir_engine_mac_muladd_16s_7ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_16s_7ns_16s_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_21_fu_66),
    .din1(grp_fu_358_p1),
    .din2(grp_fu_358_p2),
    .ce(1'b1),
    .dout(grp_fu_358_p3)
);

fir_engine_ama_addmuladd_16s_16s_5ns_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
ama_addmuladd_16s_16s_5ns_16s_16_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(empty_19_fu_58),
    .din1(empty_23_fu_74),
    .din2(grp_fu_367_p2),
    .din3(add_ln41_1_reg_488),
    .ce(1'b1),
    .dout(grp_fu_367_p4)
);

fir_engine_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln32_fu_165_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            b_fu_50 <= add_ln32_fu_171_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            b_fu_50 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_18_fu_54 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_18_fu_54 <= empty_19_fu_58;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_19_fu_58 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_19_fu_58 <= empty_20_fu_62;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_20_fu_62 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_20_fu_62 <= empty_21_fu_66;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_21_fu_66 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_21_fu_66 <= empty_22_fu_70;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_22_fu_70 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_22_fu_70 <= empty_23_fu_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_23_fu_74 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_23_fu_74 <= empty_24_fu_78;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_24_fu_78 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_24_fu_78 <= empty_25_fu_82;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_25_fu_82 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_25_fu_82 <= x_fu_222_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_46 <= 16'd0;
        end else if (((icmp_ln32_reg_447 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_fu_46 <= empty_18_fu_54;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln41_1_reg_488 <= add_ln41_1_fu_332_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        tmp_reg_471_pp0_iter2_reg <= tmp_reg_471;
        zext_ln32_reg_451_pp0_iter2_reg[4 : 0] <= zext_ln32_reg_451_pp0_iter1_reg[4 : 0];
        zext_ln32_reg_451_pp0_iter3_reg[4 : 0] <= zext_ln32_reg_451_pp0_iter2_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln32_reg_447 <= icmp_ln32_fu_165_p2;
        tmp5_reg_477 <= tmp5_fu_253_p2;
        tmp6_reg_482 <= tmp6_fu_259_p2;
        tmp_1_reg_456 <= ap_sig_allocacmp_b_1[32'd4];
        tmp_reg_471 <= tmp_fu_229_p2;
        zext_ln32_reg_451[4 : 0] <= zext_ln32_fu_177_p1[4 : 0];
        zext_ln32_reg_451_pp0_iter1_reg[4 : 0] <= zext_ln32_reg_451[4 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_165_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_reg_447 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_b_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_b_1 = b_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_in_ce0_local = 1'b1;
    end else begin
        local_in_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        local_out_ce0_local = 1'b1;
    end else begin
        local_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        local_out_we0_local = 1'b1;
    end else begin
        local_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln32_fu_171_p2 = (ap_sig_allocacmp_b_1 + 5'd1);

assign add_ln41_1_fu_332_p2 = (tmp5_reg_477 + tmp7_fu_326_p2);

assign add_ln41_3_fu_353_p2 = ($signed(grp_fu_367_p4) + $signed(grp_fu_358_p3));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_26_fu_337_p2 = tmp_reg_471_pp0_iter2_reg << 16'd6;

assign empty_27_fu_342_p2 = tmp_reg_471_pp0_iter2_reg << 16'd3;

assign empty_28_fu_241_p2 = tmp4_fu_235_p2 << 16'd3;

assign empty_29_fu_310_p2 = tmp6_reg_482 << 16'd3;

assign empty_30_fu_321_p2 = tmp6_reg_482 << 16'd1;

assign grp_fu_358_p1 = 16'd74;

assign grp_fu_358_p2 = (empty_26_fu_337_p2 - empty_27_fu_342_p2);

assign grp_fu_367_p2 = 16'd23;

assign icmp_ln32_fu_165_p2 = ((ap_sig_allocacmp_b_1 == 5'd26) ? 1'b1 : 1'b0);

assign local_in_address0 = zext_ln32_fu_177_p1;

assign local_in_ce0 = local_in_ce0_local;

assign local_out_address0 = zext_ln32_reg_451_pp0_iter3_reg;

assign local_out_ce0 = local_out_ce0_local;

assign local_out_d0 = add_ln41_3_fu_353_p2;

assign local_out_we0 = local_out_we0_local;

assign p_neg3_fu_247_p2 = (16'd0 - empty_28_fu_241_p2);

assign p_neg_fu_315_p2 = (16'd0 - empty_29_fu_310_p2);

assign tmp4_fu_235_p2 = (empty_18_fu_54 + empty_24_fu_78);

assign tmp5_fu_253_p2 = (p_neg3_fu_247_p2 - tmp4_fu_235_p2);

assign tmp6_fu_259_p2 = (empty_fu_46 + empty_25_fu_82);

assign tmp7_fu_326_p2 = (p_neg_fu_315_p2 - empty_30_fu_321_p2);

assign tmp_fu_229_p2 = (empty_20_fu_62 + empty_22_fu_70);

assign x_fu_222_p3 = ((tmp_1_reg_456[0:0] == 1'b1) ? 16'd0 : local_in_q0);

assign zext_ln32_fu_177_p1 = ap_sig_allocacmp_b_1;

always @ (posedge ap_clk) begin
    zext_ln32_reg_451[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_451_pp0_iter1_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_451_pp0_iter2_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln32_reg_451_pp0_iter3_reg[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //fir_engine_fir_engine_Pipeline_Process_Loop
